#!/usr/bin/env python
# -*- coding: utf-8 -*-
# A PsychoPy experiment is now divided in three sections. In the 
# Setup section we read files and open windows. These things are slow 
# and therefore should not be done while the experiment is running.
# in the Experiment section we do the actual presenting of stimuli
# en in the Closing section we do what has to be done after the 
# experiment if finished.
 
## Setup Section
from psychopy import core, visual
 
win = visual.Window([400,300], monitor="testMonitor")
 
# The following block of code prepares a text stimulus called message
# a numerical variable contains a number
studentNumber = 0
# a string variable contains text, it must be enclosed in quotation marks
myText = "nr:   grade:   Passed\n"
# a list variable contains a number of variables
grades = [7.1, 4.5, 6.3, 5.8, 8.2]

Passed = ["pass" if grades[0] >= 5 else "fail", "pass" if grades[1] >= 5 else "fail", "pass" if grades[2] >= 5 else "fail", "pass" if grades[3] >= 5 else "fail", "pass" if grades[4] >= 5 else "fail"]

# do something for every item in the list
for grade in grades:
    if grade  >= 5:
        feedback = 'pass'
    else:
        feedback ='fail'  
    # extend the text with one line, "\n" tells PsychoPy to start en new line
    myText += str(studentNumber) + " ,      " + str(grade) + " ,     " + str(feedback) + "\n"
    studentNumber += 1

#add the average grade
average = sum(grades)/len(grades)
myText += "\naverage: " + str(average)

# write myText to a TextStim object called message and draw this to the window
message = visual.TextStim(win, text=myText)
message.draw()
 
## Experiment Section
win.flip()
core.wait(5.0)
 
## Closing Section
win.close()
core.quit()